

services:
  postgres:
    image: postgres:16-alpine
    container_name: partizanizam_postgres
    restart: always
    environment:
      POSTGRES_USER: grobar
      POSTGRES_PASSWORD: grobar
      POSTGRES_DB: partizanizam
    ports:
      - '5432:5432'
    volumes:
      - partizanizam_pgdata:/var/lib/postgresql/data

volumes:
  partizanizam_pgdata: