

services:
  postgres:
    image: postgres:16-alpine
    container_name: partizanizam_postgres
    restart: always
    environment:
      POSTGRES_USER: partizan_user
      POSTGRES_PASSWORD: partizan_password
      POSTGRES_DB: partizanizam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: